# Generated by Django 3.0.4 on 2020-03-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prof_section', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=10)),
                ('courseID', models.CharField(max_length=10)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
    ]
